### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by MostHated** [hww/koch_fractals#1]
Hey there,
    Just wanted to pass you a quick suggestion, as I noticed that it was not structured as a Unity project. It would be super helpful if you were to upload it from the project root to include the Assets folder but then also ProjectSettings / Packages(if any used) so that Unity can detect it and open it straight away instead of having to start a new project, guess which version of Unity it was made for, then importing it, etc.

It is just much more user-friendly to be able to clone it, hit Open within Unity Hub, select the cloned folder, have it detect the Unity version, and open it from there.

Either way though, definitely a big thanks for sharing your work! It looks great!
Thanks,
-MH

**Comment by hww** [comment]
Thank You. Full project folder uploaded with last update.

**Comment by MostHated** [comment]
Great news, definitely appreciated. 👍 Also, just wanted to say I opened it up to check it out, it is pretty awesome. Thanks for sharing it!
